# Generated by Django 2.2.7 on 2023-03-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_new',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_of_person',
        ),
    ]
