# Generated by Django 2.2.7 on 2023-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230320_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=1, max_length=50, verbose_name='اللقب :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('عظام', 'عظام'), ('جلدية', 'جلدية'), ('جراحة عظام', 'جراحة عظام'), ('اطفال', 'اطفال'), ('نساء وتوليد', 'نساء وتوليد'), ('باطنة', 'باطنة'), ('جراحة عامة', 'جراحة عامة')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
    ]
