# Generated by Django 2.2.7 on 2023-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230320_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(max_length=50, verbose_name='Address detail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('عظام', 'عظام'), ('جلدية', 'جلدية'), ('جراحة عظام', 'جراحة عظام'), ('اطفال', 'اطفال'), ('نساء وتوليد', 'نساء وتوليد'), ('باطنة', 'باطنة'), ('جراحة عامة', 'جراحة عامة')], max_length=50, null=True, verbose_name='doctor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='join us'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(max_length=50, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='sur name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='waiting time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=250, verbose_name='who i'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(max_length=50, verbose_name='working hours'),
        ),
    ]
