# Generated by Django 4.1.7 on 2023-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230322_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='specialist at'),
        ),
    ]
